// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbn8BRk81ygLhpx5VLRm-wqqCMRjryG7w',
    appId: '1:263289970384:web:7821786c3e627afdba48d5',
    messagingSenderId: '263289970384',
    projectId: 'authorization-ca9f5',
    authDomain: 'authorization-ca9f5.firebaseapp.com',
    storageBucket: 'authorization-ca9f5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmbPnIy5hMgcaDalF8xhUttkkEBOAuBRg',
    appId: '1:263289970384:android:576f96f92c2818ffba48d5',
    messagingSenderId: '263289970384',
    projectId: 'authorization-ca9f5',
    storageBucket: 'authorization-ca9f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM7Aq5splRu_TzSMJ9tMQLLCRSrVdHveU',
    appId: '1:263289970384:ios:2a17fa2ec4cfb6e6ba48d5',
    messagingSenderId: '263289970384',
    projectId: 'authorization-ca9f5',
    storageBucket: 'authorization-ca9f5.appspot.com',
    iosBundleId: 'com.example.verboVoice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM7Aq5splRu_TzSMJ9tMQLLCRSrVdHveU',
    appId: '1:263289970384:ios:1c3281ee33d70072ba48d5',
    messagingSenderId: '263289970384',
    projectId: 'authorization-ca9f5',
    storageBucket: 'authorization-ca9f5.appspot.com',
    iosBundleId: 'com.example.verboVoice.RunnerTests',
  );
}
